[tool.black]
line-length = 120

[project]
name = "boogie-stats"
version = "0.1.0"
description = "A pass-through proxy for groovestats.com that records non-ranked song scores"
authors = [
    {name = "Rafał Florczak", email="florczak.raf+boogiestats@gmail.com"}
]
license = "AGPLv3"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Django (~=5.2)",
    "requests (~=2.34)",
    "gunicorn (~=26.1)",
    "django-mathfilters (~=1.0)",
    "redis (~=8.1)",
    "sentry-sdk (~=2.68)",
    "django-bootstrap-icons (==0.9.0)",
    "django-prometheus (~=2.5)",
    "prometheus-client (~=0.26)",
    "django-ipware (~=7.0)",
    "django-formset (~=2.2)",
    "tenacity (>=9.1.4,<10.0.0)",
]

[tool.poetry]
requires-poetry = ">=2.0"
packages = [
    { include = "boogiestats" },
]

[tool.poetry.requires-plugins]
poetry-plugin-shell = ">1.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1"
pytest-django = "^4.14"
black = "^26.5"
requests-mock = "^1.12.1"
flake8 = "^7.3.0"
djlint = "1.44.2"
bandit = "^1.9.4"
pre-commit = "^4.6.2"
pre-commit-hooks = "^6.0.0"
isort = "^8.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
