# Generated by Django 4.0.4 on 2022-04-22 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("machine_tag", models.CharField(max_length=4)),
                ("rivals", models.ManyToManyField(to="boogie_api.player")),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("hash", models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submission_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("score", models.IntegerField()),
                ("comment", models.CharField(max_length=200)),
                ("profile_name", models.CharField(blank=True, max_length=50, null=True)),
                ("is_top", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="boogie_api.player"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="boogie_api.song"
                    ),
                ),
            ],
        ),
    ]
