# Generated by Django 4.0.4 on 2022-05-22 19:34
import uuid

from django.db import migrations


def create_users_for_players(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    User = apps.get_model("auth", "User")
    for player in Player.objects.all():
        user = User.objects.create_user(username=uuid.uuid4().hex)
        user.save()
        player.user = user
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0002_player_user"),
    ]

    operations = [
        migrations.RunPython(create_users_for_players),
    ]
