# Generated by Django 4.0.4 on 2022-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0004_alter_player_rivals"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
