# Generated by Django 4.0.4 on 2022-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0006_alter_player_rivals"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="gs_ranked",
            field=models.BooleanField(default=False),
        ),
    ]
