# Generated by Django 4.1.1 on 2022-09-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0008_song_highscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="comment",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="song",
            name="highscore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highscore_for",
                to="boogie_api.score",
            ),
        ),
    ]
