# Generated by Django 4.1 on 2022-09-23 19:47

import django.core.validators
from django.db import migrations, models


def fixup_cmod(apps, schema_editor):
    Score = apps.get_model("boogie_api", "Score")
    for score in Score.objects.all():
        if not score.used_cmod and "C" in score.comment:
            score.used_cmod = True
            score.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0009_alter_score_comment_alter_song_highscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="profile_name",
        ),
        migrations.AddField(
            model_name="score",
            name="decents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="excellents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="fantastics",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="fantastics_plus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="greats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="has_judgments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="score",
            name="holds_held",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="mines_hit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="misses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="rate",
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name="score",
            name="rolls_held",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="total_holds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="total_mines",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="total_rolls",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="total_steps",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="score",
            name="used_cmod",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="score",
            name="way_offs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.RunPython(fixup_cmod),
    ]
