# Generated by Django 4.1 on 2022-10-03 17:54

from django.db import migrations, models
import django.db.models.deletion


def fixup_latest_scores(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    for player in Player.objects.all():
        player.latest_score = player.scores.order_by("-submission_date").first()
        player.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0010_remove_score_profile_name_score_decents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="latest_score",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_score_for",
                to="boogie_api.score",
            ),
        ),
        migrations.RunPython(fixup_latest_scores),
    ]
