# Generated by Django 4.1 on 2022-10-08 20:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0011_player_latest_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="is_top",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.PositiveIntegerField(
                db_index=True, validators=[django.core.validators.MaxValueValidator(10000)]
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="submission_date",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
