# Generated by Django 4.1 on 2022-11-14 20:50

from django.db import migrations, models
import django.utils.timezone


def fill_submission_day(apps, schema_editor):
    Score = apps.get_model("boogie_api", "Score")
    for score in Score.objects.all():
        score.submission_day = score.submission_date.date()
        score.save()


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0012_alter_score_is_top_alter_score_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="submission_day",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(fill_submission_day),
    ]
