# Generated by Django 4.0 on 2022-11-25 13:28

import django.utils.timezone
from django.db import migrations, models


def fill_join_date(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    for player in Player.objects.all():
        first_score = player.scores.order_by("submission_date").first()
        player.join_date = first_score.submission_date
        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0013_score_submission_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="join_date",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(fill_join_date),
    ]
