# Generated by Django 4.1.1 on 2023-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0014_player_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="pull_gs_name_and_tag",
            field=models.BooleanField(
                default=True,
                help_text="Pull name and tag on successful GS-ranked score submission",
                verbose_name="Pull GrooveStats name and tag",
            ),
        ),
    ]
