# Generated by Django 4.2.3 on 2023-07-22 20:52

from django.db import migrations, models
from django.db.models import Count


def fill_new_song_fields(apps, schema_editor):
    Song = apps.get_model("boogie_api", "Song")
    for song in Song.objects.all().annotate(
        num_scores=Count("scores"), num_players=Count("scores__player", distinct=True)
    ):
        song.number_of_players = song.num_players
        song.number_of_scores = song.num_scores

        song.save()


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0015_player_pull_gs_name_and_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="number_of_players",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="number_of_scores",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(fill_new_song_fields),
    ]
