# Generated by Django 4.2.3 on 2023-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0016_song_number_of_players_song_number_of_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="leaderboard_source",
            field=models.IntegerField(
                choices=[(1, "BoogieStats ITG Scores"), (2, "GrooveStats ITG Scores")], default=1
            ),
        ),
    ]
