# Generated by Django 4.2.3 on 2023-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0019_score_ex_score_score_is_ex_top_song_ex_highscore_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="leaderboard_source",
            field=models.IntegerField(
                choices=[(1, "BoogieStats ITG Scores"), (2, "GrooveStats ITG Scores"), (3, "BoogieStats EX Scores")],
                default=1,
            ),
        ),
    ]
