# Generated by Django 5.0.3 on 2024-03-09 21:04

from django.db import migrations, models


def combine_bs_leaderboard_sources(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    for player in Player.objects.filter(leaderboard_source=3):
        player.leaderboard_source = 1
        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0020_alter_player_leaderboard_source"),
    ]

    operations = [
        migrations.RunPython(combine_bs_leaderboard_sources),
        migrations.AlterField(
            model_name="player",
            name="leaderboard_source",
            field=models.IntegerField(choices=[(1, "BoogieStats"), (2, "GrooveStats")], default=1),
        ),
    ]
