# Generated by Django 5.0.3 on 2024-03-29 19:56

from django.db import migrations, models


def fill_num_scores(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    for player in Player.objects.all():
        num_scores = player.scores.count()
        player.num_scores = num_scores
        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0021_alter_player_leaderboard_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="num_scores",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(fill_num_scores),
    ]
