# Generated by Django 5.0.3 on 2024-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0022_player_num_scores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="machine_tag",
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
