# Generated by Django 5.0.3 on 2024-04-14 19:02

from django.db import migrations, models


def fill_num_songs(apps, schema_editor):
    Player = apps.get_model("boogie_api", "Player")
    for player in Player.objects.all():
        player.num_songs = player.scores.filter(is_itg_top=True).count()

        player.save()


class Migration(migrations.Migration):
    dependencies = [
        ("boogie_api", "0024_player_five_stars_player_four_stars_player_one_star_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="num_songs",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(fill_num_songs),
    ]
