# Generated by Django 5.1 on 2024-11-29 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0025_player_num_songs"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="bluesky_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=253,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="bokutachi_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="discord_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="kamaitachi_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="twitch_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=25,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="twitter_x_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
                verbose_name="Twitter/X handle",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="youtube_handle",
            field=models.CharField(
                blank=True,
                default="",
                max_length=30,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z_\\-\\.]+$",
                        "Only alphanumeric characters, underscores, dashes and periods are allowed.",
                    ),
                ],
            ),
        ),
    ]
