# Generated by Django 5.2.11 on 2026-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boogie_api", "0027_player_gs_integration_score_gs_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="gs_integration",
            field=models.IntegerField(
                choices=[(1, "Require GrooveStats"), (2, "Try GrooveStats"), (3, "Skip GrooveStats")],
                default=2,
                help_text="This option defines the behavior on score submission.\n            <ul>\n            <li>Require GrooveStats (discouraged, old default) will respond with a failure to the game when there's been an error / timeout during score submission to GS and will not save the score in BS in such cases. This can result in scores actually being saved in GS but not in BS.</li>\n            <li>Try GrooveStats (recommended, new default) will attempt to send the score to GrooveStats and despite of the result, save the score in BS. You can filter such scores on your profile page and manually submit them again or mark them as submitted.</li>\n            <li>Skip GrooveStats can be used when you don't care about GS or the events like ITL/SRPG. It will save your scores only in BS for the best score submission performance. You can still manually submit them to GS later from the UI using GS QR-code API.</li>\n            </ul>",
                verbose_name="GrooveStats Integration",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="leaderboard_source",
            field=models.IntegerField(
                choices=[(1, "BoogieStats"), (2, "GrooveStats")],
                default=1,
                help_text="In-game leaderboards source. When GrooveStats is selected, it might still fall back to BoogieStats in case of GS errors or timeouts. This setting will be ignored when GrooveStats Integration is set to Skip GrooveStats.",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="pull_gs_name_and_tag",
            field=models.BooleanField(
                default=True,
                help_text="Pull & update player name and machine tag on successful score submission to GrooveStats. This setting will be ignored when GrooveStats Integration is set to Skip GrooveStats.",
                verbose_name="Pull GrooveStats name and machine tag",
            ),
        ),
    ]
